// Restored from ref/webview/assets/app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~mfl5y5w0-BM8XTFln.js
// Exact historical bundle match re-exporting the reviewed semantic authority.
export {
  interpolate,
  initAnimatePresenceRuntime,
  initMotionValueClassRuntime,
  MotionValue,
  initCubicBezierRuntime,
  clamp,
  motionValue,
  initClampRuntime,
  AnimatePresence,
  useIsPresent,
  useMotionValueEvent,
  initAnimateRuntime,
  MotionConfig,
  initUseSpringRuntime,
  useTransform,
  initMotionTemplateRuntime,
  initUseMotionValueEventRuntime,
  useMotionValue,
  animate,
  cubicBezier,
  initInterpolateRuntime,
  useSpring,
  initUseMotionValueRuntime,
  initDragControlsRuntime,
  initReducedMotionRuntime,
  useMotionTemplate,
  useDragControls,
  useReducedMotion,
  initFramerMotionCurrentRuntime,
  initUseTransformRuntime,
  initMotionComponentRuntime,
  initPresenceRuntime,
  initMotionConfigRuntime,
  motion,
} from "./index";
