// Restored from ref/webview/assets/browser-use-settings-Ct3jD7gG.js
//
// TYPED BOUNDARY FACADE (generated by manual stage-3 restoration).
// Semantic aliases for Chromium settings constants exported by src-l0hbMZ-p.
/* eslint-disable @typescript-eslint/no-explicit-any */

export {
  _srcEr as CHROME_SITE_SETTINGS_URL,
  _srcIr as getChromeSiteDetailsUrlForSite,
  _srcNr as CHROME_COOKIES_URL,
  _srcTr as SITE_SETTINGS_PARTITION,
  _srcZn as CHROME_PROTOCOL_HANDLERS_URL,
  srcBn as BROWSER_DOWNLOADS_SETTINGS_PATH,
  srcGn as EXTENSION_SETTINGS_PARTITION,
  srcHn as HISTORY_SETTINGS_PARTITION,
  srcIn as CONTACT_INFO_ROOT_URLS,
  srcJn as CHROME_PASSWORDS_URL,
  srcKn as CHROME_PASSWORD_MANAGER_URL,
  srcLn as BROWSER_CONTACT_INFO_SETTINGS_PATH,
  srcN as BROWSER_SITE_SETTINGS_ROUTE_PATTERN,
  srcQn as BROWSER_PASSWORD_SETTINGS_PATH,
  srcRn as CHROME_CONTACT_INFO_URL,
  srcUn as BROWSER_EXTENSIONS_SETTINGS_PATH,
  srcVn as CHROME_DOWNLOADS_URL,
  srcWn as CHROME_EXTENSIONS_URL,
  srcYn as PASSWORD_MANAGER_PARTITION,
  srcZn as CONTACT_INFO_PARTITION,
} from "../../boundaries/src-l0hb-mz-p";
