// Restored from ref/webview/assets/esm-Y-tKzZee.js
// Current Segment Analytics Core runtime reuses the byte-identical npm adapter.
export {
  isString,
  pTimeout,
  isFunction,
  initValidationRuntime,
  isNumber,
  initCallbackRuntime,
  initCoreEventFactory,
  initDeferredEmitterRuntime,
  initCoreEventQueue,
  createDeferred,
  ContextCancelation,
  CoreStats,
  initCoreStats,
  initPriorityQueue,
  PriorityQueue,
  CoreEventQueue,
  isPlainObject,
  CoreContext,
  createMessageId,
  dispatch,
  attempt,
  initUuidRuntime,
  initDispatchRuntime,
  initPluginRuntime,
  initSegmentAnalyticsCore,
  initCoreContext,
  Emitter,
  CoreEventFactory,
  initCreateDeferred,
  initEmitter,
} from "../../package-adapters/segment-analytics-core-1-8-2";
