// Restored from ref/webview/assets/presentation-CUZjJ-AQ.js
// Semantic presentation-schema barrel backed by the restored current runtime.
import {
  ___presentationT as AvLst,
  ___presentationN as BodyProperties,
  _presentationR as Camera3D,
  _presentationI as ChartReference,
  _presentationA as CodeBlockElement,
  presentationO as CodeBlockKind,
  _presentationS as CodeEnvironment,
  _presentationC as CodeExecutionMeta,
  _presentationL as CodeLineRange,
  _presentationU as CodeResult,
  _presentationD as CodeThemeRef,
  _presentationF as ColorMap,
  presentationP as ColorScheme,
  _presentationM as ConditionalTableStyle,
  presentationH as ConditionalTableStyle_Condition,
  presentationG as Connector,
  presentationUnderscore as ConnectorLineStyle,
  presentationV as ConnectorLineStyle_LineCap,
  _presentationY as ConnectorLineStyle_LineEnd,
  presentationB as ConnectorLineStyle_LineEndLength,
  presentationX as ConnectorLineStyle_LineEndType,
  presentationS as ConnectorLineStyle_LineEndWidth,
  presentationC as ConnectorLineStyle_LineJoin,
  _presentationW as CustomPath,
  __presentationT as Effect,
  presentationE as EffectStyle,
  presentationD as EffectType,
  presentationElement as Element,
  presentationK as ElementPlacement,
  presentationA as ElementPlacementType,
  presentationJ as ElementType,
  presentationM as ElementWrap,
  __presentationN as ElementWrapType,
  _presentationP as EmbeddedArtifactElement,
  presentationF as EmbeddedFont,
  presentationI as EmbeddedFontType,
  presentationL as FontDefinition,
  __presentationR as GlowEffect,
  presentationZ as Hyperlink,
  _presentationB as ImageElement,
  _presentationV as ImageMask,
  _presentationH as InlineNode,
  presentationU as Layout,
  presentationW as LightRig3D,
  presentationParagraph as Paragraph,
  _presentationK as PathArcTo,
  presentationQ as PathClose,
  _presentationJ as PathCommand,
  presentationY as PathCubicBezierTo,
  _presentationX as PathLineTo,
  _presentationZ as PathMoveTo,
  _presentationQ as PathQuadBezierTo,
  presentationDollar as Presentation,
  presentationEt as PresentationGuide,
  presentationTt as PresentationGuide_GuideOrientation,
  presentationNt as PresentationViewProperties,
  _presentationRt as RectFormula,
  presentationReflectionEffect as ReflectionEffect,
  presentationAt as Rotation3D,
  presentationOt as Scene3D,
  _presentationSt as Script,
  presentationCt as Script_ReturnMode,
  presentationUt as Shape3D,
  presentationDt as Shape3D_Bevel,
  presentationShape as ShapeElement,
  presentationPt as Slide,
  presentationMt as SlideFurnitureVisibility,
  presentationHt as SmartArtConnection,
  presentationGt as SmartArtDataModel,
  _presentationT as SmartArtElement,
  presentationVt as SmartArtLayoutAlgorithm,
  _presentationYt as SmartArtLayoutAtom,
  presentationBt as SmartArtLayoutChoose,
  _presentationXt as SmartArtLayoutChooseBranch,
  presentationSt as SmartArtLayoutConstraint,
  _presentationCt as SmartArtLayoutConstraints,
  presentationWt as SmartArtLayoutForEach,
  _presentationTt as SmartArtLayoutIterator,
  _presentationEt as SmartArtLayoutNode,
  _presentationDt as SmartArtLayoutParameter,
  _presentationOt as SmartArtLayoutPresentationOf,
  presentationKt as SmartArtLayoutRule,
  _presentationAt as SmartArtLayoutRules,
  presentationJt as SmartArtLayoutShape,
  _presentationMt as SmartArtPoint,
  _presentationNt as SoftEdgesEffect,
  _presentationPt as StyleReference,
  presentationFt as TableBorder,
  presentationIt as TableBorders,
  presentationLt as TableCell,
  presentationRt as TableCellBorders,
  presentationZt as TableCellMargins,
  _presentationBt as TableCellStyle,
  _presentationVt as TableCell_Lines,
  _presentationHt as TableElement,
  _presentationUt as TableProperties,
  _presentationWt as TableRow,
  _presentationGt as TableStyleDefinition,
  _presentationKt as TableStylePart,
  presentationQt as TableStyles,
  _presentationJt as TextRun,
  presentationTheme as Theme,
  presentationXt as ThemeColor,
  presentationObjectDefaults as ThemeObjectDefaults,
  _presentationZt as VideoElement,
  presentationT as protobufPackage,
  initPresentationSchemaPartA as initPresentationSemanticBarrel,
} from "../presentation-current";
initPresentationSemanticBarrel();
export {
  AvLst,
  BodyProperties,
  Camera3D,
  ChartReference,
  CodeBlockElement,
  CodeBlockKind,
  CodeEnvironment,
  CodeExecutionMeta,
  CodeLineRange,
  CodeResult,
  CodeThemeRef,
  ColorMap,
  ColorScheme,
  ConditionalTableStyle,
  ConditionalTableStyle_Condition,
  Connector,
  ConnectorLineStyle,
  ConnectorLineStyle_LineCap,
  ConnectorLineStyle_LineEnd,
  ConnectorLineStyle_LineEndLength,
  ConnectorLineStyle_LineEndType,
  ConnectorLineStyle_LineEndWidth,
  ConnectorLineStyle_LineJoin,
  CustomPath,
  Effect,
  EffectStyle,
  EffectType,
  Element,
  ElementPlacement,
  ElementPlacementType,
  ElementType,
  ElementWrap,
  ElementWrapType,
  EmbeddedArtifactElement,
  EmbeddedFont,
  EmbeddedFontType,
  FontDefinition,
  GlowEffect,
  Hyperlink,
  ImageElement,
  ImageMask,
  InlineNode,
  Layout,
  LightRig3D,
  Paragraph,
  PathArcTo,
  PathClose,
  PathCommand,
  PathCubicBezierTo,
  PathLineTo,
  PathMoveTo,
  PathQuadBezierTo,
  Presentation,
  PresentationGuide,
  PresentationGuide_GuideOrientation,
  PresentationViewProperties,
  RectFormula,
  ReflectionEffect,
  Rotation3D,
  Scene3D,
  Script,
  Script_ReturnMode,
  Shape3D,
  Shape3D_Bevel,
  ShapeElement,
  Slide,
  SlideFurnitureVisibility,
  SmartArtConnection,
  SmartArtDataModel,
  SmartArtElement,
  SmartArtLayoutAlgorithm,
  SmartArtLayoutAtom,
  SmartArtLayoutChoose,
  SmartArtLayoutChooseBranch,
  SmartArtLayoutConstraint,
  SmartArtLayoutConstraints,
  SmartArtLayoutForEach,
  SmartArtLayoutIterator,
  SmartArtLayoutNode,
  SmartArtLayoutParameter,
  SmartArtLayoutPresentationOf,
  SmartArtLayoutRule,
  SmartArtLayoutRules,
  SmartArtLayoutShape,
  SmartArtPoint,
  SoftEdgesEffect,
  StyleReference,
  TableBorder,
  TableBorders,
  TableCell,
  TableCellBorders,
  TableCellMargins,
  TableCellStyle,
  TableCell_Lines,
  TableElement,
  TableProperties,
  TableRow,
  TableStyleDefinition,
  TableStylePart,
  TableStyles,
  TextRun,
  Theme,
  ThemeColor,
  ThemeObjectDefaults,
  VideoElement,
  protobufPackage,
};
