// Restored from ref/webview/assets/index-CwTZhj1W.js
// Flat generated current-build implementation used by the positional adapter.
const __vite__mapDeps = (
  indexParam1,
  indexParam2 = __vite__mapDeps,
  indexParam3 = indexParam2.f ||
    (indexParam2.f = [
      "./rpc-YvKadVpS.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~l16cgjx9-Bw-xR9Fl.js",
      "./rolldown-runtime-BG2f4sTM.js",
      "./app-initial~avatarOverlayCompositionSurface~index-9fQ9wihu~index-BFCcxPM5~mapbox-gl-DVWlwqb~kppdhley-mFmI6cbL.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~ngwudnyz-CS1L_Amm.js",
      "./app-initial~avatarOverlayCompositionSurface~index~index-9fQ9wihu~index-BFCcxPM5~mapbox-gl-D~ch0na97m-DGJ4C9j8.js",
      "./app-main-DScr-fiP.js",
      "./app-initial~avatarOverlayCompositionSurface~index-9fQ9wihu~index-BFCcxPM5~mapbox-gl-DVWlwqb~gsbyx6su-Cok-LK6_.js",
      "./app-initial~avatarOverlayCompositionSurface~index-9fQ9wihu~index-BFCcxPM5~mapbox-gl-DVWlwqb~elr7dp2m-f2m0c2c7.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~cc80cam6-Z-xASB4J.js",
      "./app-DN8cEaiB.js",
      "./app-B6aXltj2.css",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~k8lpzggp-C0GSl6LK.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~dejrazf4-CutsMNtQ.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~business-checkout~oxnpxkxc-Caq74mjw.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~g8980z4e-Bj4tUPiN.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~l0zkuzaj-DDSIe85-.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~nssizff1-C8BmUbuQ.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~business-checkout~c1u3yp5s-DJt4asyD.js",
      "./app-initial~avatarOverlayCompositionSurface~app-main~pet-install-modal-host~quick-chat-wind~oieh6gbs-7op9FAJ2.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~dg0b1kws-Cm26-F9e.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~cx4spki5-DbAq9-24.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~gqsmt9fs-dLL3MXt8.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~o47g1ejz-BCk6yZ5U.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~mfl5y5w0-BM8XTFln.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~kr7rxhqe-BlMllWZR.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~app-main~first-ru~io63sqtc-DdjCxUFR.js",
      "./app-initial~artifact-tab-content.electron~app-main~page~pull-request-code-review~new-thread~b942ryfo-CUxnPNK1.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~pull-request-rout~e3eqjujm-CMCtzrpZ.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~pull-request-rout~b0wqjrxp-BxI_oO_W.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~business-checkout~mgfw3nls-C1ihWWPl.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~business-checkout~k87y25tw-31XubniU.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~business-checkout~djgpmkub-Df7Ywx3x.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~pull-request-rout~efr39kk0-DNJEe78y.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~pull-request-rout~gocinqla-CZ30ZsFv.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~settings-command-~cajo70vh-C4Uu6T2D.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~settings-command-~hox8u96i-DU7nfKAJ.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~appgen-settings-p~enk8v32p-D1DRfRxz.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~settings-command-~muf4xbuf-fD-zXwqV.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~business-checkout~h49w84u1-Drk2yoP4.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~settings-command-~ktg7n5fh-CyJP3GkW.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~pull-request-rout~ij9syevn-Bd6vNL2C.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~appgen-settings-p~gy16mplo-E7l_I04F.js",
      "./app-initial~artifact-tab-content-DWZWEf8S.css",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~settings-command-~eurqfy6e-BYVE1srw.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~settings-command-~fpqaaiae-BoQBkWFV.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~appgen-settings-p~dl1mfg21-CewNvCnh.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~first-run~appgen-~e0dsm8dr-CV2ly3l2.js",
      "./app-initial~artifact-tab-content.electron~app-main~appgen-settings-page~page~pull-request-r~ll1u4x0e-Bl9B7AEa.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~settings-command-~ea2v0nlw-CpgLJdNt.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~pull-request-rout~ns5rw1zk-CeyyTou6.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~iaq4jiqv-Cyrw3qv2.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~lwcln7a4-DZ9RGu5U.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~notebook-preview-~fgrgw77v-B-sYQokA.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~first-run~appgen-~c5cc47t8-kVI3IP2t.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~appgen-settings-p~efg7nxh1-BkQYZ_Iz.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~settings-command-~ab38dkdb-BD-y9IYB.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~pull-request-rout~hyp4gsv8-Dz2dJTEh.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~settings-command-~oj3xzvw5-D5NeZ8w8.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~settings-command-~jxrd5329-BVfs8R0W.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~appgen-settings-p~evbmo86c-BIxmPNYv.js",
      "./app-initial~artifact-tab-content-P5CHkazr.css",
      "./app-initial~avatarOverlayCompositionSurface~app-main~new-thread-panel-page~onboarding-page~~e9wvq029-CiPbJSBe.js",
      "./app-initial~avatarOverlayCompositionSurface~app-main~settings-command-menu-section-items~ne~oh4ipvq7-Bzl9Xgx0.js",
      "./app-initial~avatarOverlayCompositionSurface~notebook-preview-panel~app-main~appgen-settings~el5fc9d5-B8voNEr1.js",
      "./app-initial~app-main~plugin-detail-page~new-thread-panel-page~onboarding-page~appgen-librar~zbesvgjb-GR_E01Nt.js",
      "./app-initial~artifact-tab-content.electron~app-main~plugin-detail-page~new-thread-panel-page~buikfm6j-DPrq925a.js",
      "./app-initial~app-main~settings-command-menu-section-items~first-run~plugin-detail-page~new-t~md593oel-D9Ni1kuk.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~app-main~appgen-s~j5d6n91g-C7rMDXCx.js",
      "./app-initial~artifact-tab-content.electron~app-main~appgen-settings-page~page~pull-request-r~i9veoilb-2NQd-tpH.js",
      "./app-initial~artifact-tab-content.electron~app-main~appgen-settings-page~page~pull-request-r~mxek7o2y-DNfRAQRH.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~appgen-settings-p~jj50pjos-DTKLRB5p.js",
      "./app-initial~artifact-tab-content.electron~app-main~appgen-settings-page~page~pull-request-r~jkcpinc3-UWDvHayW.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content-DJDX7Pvr.css",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~b6mb9dk4-gMHmseWC.js",
      "./app-initial~avatarOverlayCompositionSurface~app-main~new-thread-panel-page~onboarding-page~~e9wvq029-DqStEw03.css",
      "./app-initial~avatarOverlayCompositionSurface~app-main~new-thread-panel-page~onboarding-page~~kgjrczv7-DHLi4c_J.js",
      "./app-initial~avatarOverlayCompositionSurface~artifact-tab-content.electron~app-main~plugin-d~kw7nl1sl-CSfXbWX3.js",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~projects-index-page~appgen-libra~2gcv58yj-TpRFuuJ5.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~jnqazr7u-CT80B0yW.js",
      "./app-initial~artifact-tab-content-ptHiDCW_.css",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-route~pull-request-code-rev~bjz2nm8r-D-vI0dpV.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-route~pull-request-code-rev~fzrvbq9l-sutawCMW.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~ntg60hiq-7MggXT9j.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-route~pull-request-code-rev~ohfl1njq-DAURm7My.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~pull-request-rout~jvsvjxtt-B-CZ9DhL.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~pull-request-rout~k0tdw7da-C1uINtmZ.js",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~appgen-settings-p~b4s0c4vd-JAh37hFt.js",
      "./app-initial~artifact-tab-content-BTleCTWE.css",
      "./app-initial~artifact-tab-content.electron~notebook-preview-panel~app-main~pull-request-rout~kxr6s7fb-BUajY5gG.js",
      "./app-initial~artifact-tab-content-B1OX0T1M.css",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~appgen-library-page~hotkey-windo~im5yc0bw-BlqwAlDd.js",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~projects-index-page~appgen-libra~egjdcxue-ni-ZiM6f.js",
      "./app-initial~artifact-tab-content.electron~app-main~appgen-settings-page~page~pull-request-c~cmwz7z7b-mvKtPvzV.js",
      "./app-initial~artifact-tab-content.electron~app-main~settings-command-menu-section-items~pull~opk4tq05-DfKz3rni.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~dixfr41z-DyJqY6c7.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~o1pkxa0i-CReILizo.js",
      "./app-initial~artifact-tab-content.electron~app-main~appgen-settings-page~pull-request-route~~pdazrfmg-DzasxZnO.js",
      "./app-initial~artifact-tab-content.electron~app-main~new-thread-panel-page~onboarding-page~pr~gh55pyj3-C7xUNhuM.js",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~projects-index-page~appgen-libra~cci0ubce-B3AG916S.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~kxdmdety-Dw15wju7.js",
      "./app-initial~artifact-tab-content.electron~app-main~new-thread-panel-page~onboarding-page~se~ismvjv52-DOg-s8wB.js",
      "./app-initial~artifact-tab-content.electron~app-main~settings-command-menu-section-items~pull~olm3nzne-DR0PxsC_.js",
      "./app-initial~artifact-tab-content-EBEHrbNH.css",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~mof41p1g-BrARXrS8.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~nmo0zeut-CjpSBAIY.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~k9hi4mli-JxBCaUwM.js",
      "./app-initial~artifact-tab-content-BF8TOyej.css",
      "./app-initial~artifact-tab-content-yrUTdPBm.css",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~projects-index-page~appgen-libra~egjdcxue-CYswclfQ.css",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~projects-index-page~appgen-libra~ke3j1rk8-BsD1GFS2.js",
      "./app-initial~avatarOverlayCompositionSurface~app-main~pull-request-route~plugin-detail-page~~hj7snlk9-AhvxeLxv.js",
      "./app-initial~app-main~pull-request-route~onboarding-page~projects-index-page~hotkey-window-t~mgwh6spa-B8-rSDzI.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~hk3gicj1-CqC9dSHh.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~emmhcg7r-BZxg6ar5.js",
      "./app-initial~app-main~appgen-settings-page~pull-request-route~plugin-detail-page~onboarding-~j9yriubg-BNsnCk5_.js",
      "./app-initial~artifact-tab-content.electron~app-main~pull-request-code-review~new-thread-pane~hrquzmi2-BffmFVeO.js",
      "./app-initial~avatarOverlayCompositionSurface~app-main~new-thread-panel-page~onboarding-page~~kgjrczv7-DchTwzxU.css",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~appgen-library-page~hotkey-windo~l46phxln-D0OL-Wu_.js",
      "./app-initial~app-main~settings-command-menu-section-items~new-thread-panel-page~onboarding-p~gtr83nev-DLC7obGh.js",
      "./app-initial~app-main~onboarding-page~hotkey-window-thread-page~quick-chat-window-page~chatg~f5p8e1kp-B1NDMoKY.js",
      "./app-initial~app-main~onboarding-page~hotkey-window-thread-page~quick-chat-window-page~chatg~nejl6ozr-CW_aiF_H.js",
      "./app-initial~artifact-tab-content.electron~app-main~new-thread-panel-page~onboarding-page~pr~zrwbgkzl-CegZRLSz.js",
      "./app-initial~app-main~settings-command-menu-section-items~pull-request-route~new-thread-pane~fnoshreu-D5mfSDoa.js",
      "./app-initial~app-main~settings-command-menu-section-items~pull-request-route~new-thread-pane~fnoshreu-B6-UZ6B5.css",
      "./app-initial~app-main~pull-request-route~new-thread-panel-page~onboarding-page~projects-inde~ldmpswh9-BbClLuNw.js",
      "./app-initial~artifact-tab-content.electron~app-main~first-run~pull-request-code-review~new-t~fmb7ipbs-CpNuSQYh.js",
      "./app-initial~artifact-tab-content-uRuhKLE-.css",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~projects-index-page~appgen-libra~im95otkx-f2gK70L9.js",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~projects-index-page~appgen-libra~im95otkx-BrqwKW_G.css",
      "./app-initial~artifact-tab-content.electron~app-main~new-thread-panel-page~onboarding-page~pr~blkpjiml-xAZlgtpH.js",
      "./app-initial~artifact-tab-content.electron~app-main~new-thread-panel-page~onboarding-page~pr~o8t3lko6-tYwNiF7d.js",
      "./app-initial~artifact-tab-content-DBJd2MnX.css",
      "./app-initial~app-main~onboarding-page~hotkey-window-thread-page~hotkey-window-home-page~quic~nn8qcn6y-BBOcTlwy.js",
      "./app-initial~app-main~onboarding-page~projects-index-page~hotkey-window-thread-page~hotkey-w~klbdzshd-BgKzs-_j.js",
      "./app-initial~app-main~onboarding-page~projects-index-page~plan-summary-page~hotkey-window-th~e5sxdgia-CO27APJz.js",
      "./app-initial~app-main~onboarding-page~projects-index-page~plan-summary-page~hotkey-window-th~e5sxdgia-C6cWVbB-.css",
      "./app-initial~app-main~new-thread-panel-page~appgen-library-page~hotkey-window-thread-page~ho~jhj9i1pn-Cu26CgZz.js",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~appgen-library-page~hotkey-windo~i1qg4eb0-Ds65-jeS.js",
      "./app-initial~app-main~settings-command-menu-section-items~new-thread-panel-page~settings-pag~bzu8y8ld-D7hTna0M.js",
      "./app-initial~app-main~new-thread-panel-page~settings-page~projects-index-page~appgen-library~lo3xk1s3-Bb2oBtuk.js",
      "./app-initial~app-main~pull-request-route~plugin-detail-page~new-thread-panel-page~appgen-lib~n5mozedo-DyaB_rqV.js",
      "./app-initial~app-main~new-thread-panel-page~appgen-library-page~hotkey-window-thread-page~ho~jhj9i1pn-BQcvecIn.css",
      "./app-initial~app-main~projects-index-page~quick-chat-window-page~chatgpt-conversation-page-CnNMwyju.js",
      "./app-initial~app-main~settings-command-menu-section-items~settings-page~projects-index-page~~kp2udj4a-CtM1Oc6W.js",
      "./app-initial~app-main~onboarding-page~projects-index-page~quick-chat-window-page~codex-micro~iqsnin5k-BAAEpSZN.js",
      "./app-initial~app-main~quick-chat-window-page~chatgpt-conversation-page~composer-project-sele~kuwa4oig-KfD6QNXg.js",
      "./app-initial~app-main~projects-index-page~hotkey-window-new-thread-page~hotkey-window-home-p~dw4jijov-C2WWQYCH.js",
      "./app-initial~app-main~pull-request-route~onboarding-page~hotkey-window-thread-page~quick-cha~mo2avlln-9Z3G5P1M.js",
      "./app-initial~app-main~onboarding-page~hotkey-window-thread-page~quick-chat-window-page~chatg~c33rimzq-BWHGLvUG.js",
      "./app-initial~app-main~onboarding-page~hotkey-window-thread-page~quick-chat-window-page~chatg~b1ew1ta1-BTnGMpyz.js",
      "./app-initial~app-main~settings-command-menu-section-items~first-run~plugin-detail-page~onboa~eoalflv1-Bx7RD-t-.js",
      "./app-initial~app-main~pull-request-route~pull-request-code-review~onboarding-page~projects-i~gmpr6uvf-BT7S7DYV.js",
      "./app-initial~app-main~business-checkout-switch-workspace-dialog~appgen-settings-page~plugin-~kzake19j-D6CdEHGR.js",
      "./app-initial~app-main~onboarding-page~hotkey-window-thread-page~quick-chat-window-page~chatg~kmcnquzv-B_s2nD8t.js",
      "./app-initial~app-main~pull-request-code-review~onboarding-page~projects-index-page~hotkey-wi~cl652svh-aipyKrLh.js",
      "./app-initial~app-main~pull-request-code-review~onboarding-page~projects-index-page~hotkey-wi~cl652svh-updTK7TW.css",
      "./app-initial~app-main~pull-request-code-review~onboarding-page~hotkey-window-thread-page~qui~fu5v6bw6-BlsHIQHg.js",
      "./app-initial~app-main~page~pull-request-route~onboarding-page~appgen-library-page~hotkey-win~lehncapg-BMtUKwiQ.js",
      "./app-initial~app-main~page~pull-request-route~onboarding-page~appgen-library-page~hotkey-win~lehncapg-H4NGgmRi.css",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~hotkey-window-thread-page~quick-~e9bovb3h-BHZCNGGg.js",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~hotkey-window-thread-page~quick-~e9bovb3h-CxuoHau6.css",
      "./app-initial~app-main~onboarding-page~hotkey-window-thread-page~quick-chat-window-page~chatg~c33rimzq-BCw0GX57.css",
      "./app-initial~app-main~page~quick-chat-window-page~chatgpt-conversation-page-BJ2Dcu2L.js",
      "./app-initial~app-main~page~onboarding-page~quick-chat-window-page~chatgpt-conversation-page-ltrENp5i.js",
      "./app-initial~app-main~page~quick-chat-window-page~chatgpt-conversation-page-Bps-0OA4.css",
      "./app-initial~avatarOverlayCompositionSurface~app-main~pet-install-modal-host~quick-chat-wind~oieh6gbs-W6svNPuO.css",
      "./app-initial~app-main~codex-micro-settings~keyboard-shortcuts-settings~codex-micro-joystick-~oakijxdz-DppMeWM8.js",
      "./app-initial~app-main~appgen-settings-page~page~appgen-library-page~appgen-page~appgen-setti~ogh9jurw-C1AmS95p.js",
      "./app-initial~avatarOverlayCompositionSurface~app-main~debug-settings~codex-micro-settings~co~gdbfobd5-COLdNkST.js",
      "./app-initial~app-main~new-thread-panel-page~codex-micro-settings~codex-micro-onboarding-host~ei5mtuuv-Dd4yTOOV.js",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~projects-index-page~appgen-libra~h58kqoyf-zwEs2Ce9.js",
      "./app-initial~app-main~new-thread-panel-page~appgen-library-page~hotkey-window-thread-page~ho~crseajay-C22uONlO.js",
      "./app-initial~app-main~new-thread-panel-page~appgen-library-page~hotkey-window-thread-page~ho~ks79et1p-BUQVTvo7.js",
      "./app-initial~app-main~new-thread-panel-page~appgen-library-page~hotkey-window-thread-page~ho~ks79et1p-D3jrmUOb.css",
      "./app-initial~avatarOverlayCompositionSurface~app-main~hotkey-window-thread-page~avatar-overl~ivlwwypn-DZ5hMBGt.js",
      "./app-initial~app-main~settings-command-menu-section-items~new-thread-panel-page~settings-pag~ie5db62r-B0pIQt19.js",
      "./app-initial~app-main~settings-command-menu-section-items~settings-page~projects-index-page~~hbq5ge6k-CtslB5AX.js",
      "./app-initial~app-main~pull-request-route~new-thread-panel-page~appgen-library-page~hotkey-wi~l9h1w628-BK7DJJ7b.js",
      "./app-initial~app-main~pull-request-route~new-thread-panel-page~appgen-library-page~hotkey-wi~l9h1w628-BT0Fr19o.css",
      "./app-initial~app-main~settings-command-menu-section-items~settings-page~codex-mobile-page~de~jwxee9zo-gUiO2sMu.js",
      "./app-initial~app-main~new-thread-panel-page~projects-index-page~appgen-library-page~hotkey-w~gvw9nkdu-BIKEUPPl.js",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~select-workspace-page~login-rout~ed992cau-B1vrGsWe.js",
      "./app-initial~app-main~onboarding-page~projects-index-page~hotkey-window-thread-page~chatgpt-~j34jmud9-DNuPQHcp.js",
      "./app-initial~app-main~pull-request-route~projects-index-page~hotkey-window-thread-page~hotke~ky26iy0f-C8jdF-F9.js",
      "./app-initial~app-main~onboarding-page~projects-index-page~hotkey-window-thread-page~chatgpt-~j34jmud9-Bj9zvK4d.css",
      "./app-initial~app-main~settings-command-menu-section-items~new-thread-panel-page~settings-pag~unq8yzli-B-Ca7uGT.js",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~appgen-library-page~hotkey-windo~k4644ppc-DWhJzK0F.js",
      "./app-initial~app-main~new-thread-panel-page~appgen-library-page~hotkey-window-thread-page~ho~oblsrohm-CVk3HtWg.js",
      "./app-initial~app-main~hotkey-window-thread-page~local-environments-settings-page~thread-app-~nhni7vug-TPlsqCkm.js",
      "./app-initial~app-main~onboarding-page~hotkey-window-thread-page~debug-window-page~appearance~o4fm6wvw-C20BtzWH.js",
      "./app-initial~app-main~new-thread-panel-page~onboarding-page~plan-summary-page~hotkey-window-~fdec98zn-B9a1sNdv.js",
      "./app-initial~app-main~onboarding-page~hotkey-window-thread-page~thread-app-shell-chrome~remo~c1415s9d-CF24qAIu.js",
      "./app-initial~app-main~projects-index-page~chatgpt-conversation-page~remote-connections-setti~ih6lkeby-DaQtgNXa.js",
      "./app-initial~app-main~onboarding-page~hotkey-window-new-thread-page~hotkey-window-home-page~~or65j7iw-CbYJGWGO.js",
      "./app-initial~app-main~onboarding-page~select-workspace-page~projects-index-page~debug-window~gzajiv46-C-hCXltq.js",
      "./app-initial~notebook-preview-panel~app-main~pull-request-route~projects-index-page~cloud-en~lpx9dmpy-CP_V9_i3.js",
      "./app-initial~app-main~pull-request-route~pull-request-code-review~projects-index-page~chatgp~de4b76nn-CMXmm90b.js",
      "./app-initial~app-main~plugin-detail-page~settings-page~projects-index-page~appgen-library-pa~nsqr45u8-C3he6mAT.js",
      "./app-initial~app-main~appgen-library-page~remote-conversation-page~local-conversation-page-DqgfEyEM.js",
      "./app-initial~app-main~first-run~new-thread-panel-page~onboarding-page-9GAwL4-7.js",
      "./app-initial~app-main~onboarding-page~mermaid-diagram~xychartDiagram-PRI3JC2R~timeline-defin~dcen2xty-DF12FUR9.js",
      "./app-initial~app-main~business-checkout-switch-workspace-dialog~settings-page~login-route~co~0rxi42yi-C46MKoy-.js",
      "./app-initial~app-main~onboarding-page~select-workspace-page~login-route~pets-settings~appear~d8wa6t8l-C7KL1yO4.js",
      "./app-initial~app-main~pull-request-route~onboarding-page~appearance-settings~import-settings~g003p0gq-_mU55TW2.js",
      "./app-initial~app-main~appgen-library-page~quick-chat-window-page~cloud-environments-settings~jm17temy-DDtEkXKS.js",
      "./app-initial~app-main~settings-command-menu-section-items~appgen-settings-page~page~pull-req~nb6vzw6f-CtpDXO6Z.js",
      "./app-initial~app-main~appgen-library-page~quick-chat-window-page~cloud-environments-settings~jm17temy-wE6gH43W.css",
      "./app-initial~app-main~checkout-webview-page-C-JxhURz.js",
      "./app-initial~app-main~appgen-settings-page~page~appgen-library-page~appgen-page~appgen-setti~ogh9jurw-CoRkWt-2.css",
    ]),
) => indexParam1.map((item) => indexParam3[item]);
import { createLazyEsmInitializer as rolldownRuntimeN } from "../rolldown-runtime";
import { installModulepreloadPolyfill as ModulepreloadPolyfill } from "../modulepreload-polyfill";
import {
  preloadModule as appInitialAvatarOverlayCompositionSurfaceIndexIndex9fQ9wihuIndexBFCcxPM5MapboxGlDCh0na97mO,
  initPreloadRuntime as appInitialAvatarOverlayCompositionSurfaceIndexIndex9fQ9wihuIndexBFCcxPM5MapboxGlDCh0na97mS,
} from "../app-initial~avatar-overlay-composition-surface~index~index-9f-q9wihu~index-bfccx-pm5~mapbox-gl-d~ch0na97m";
var indexValue1 = rolldownRuntimeN(() => {}),
  indexValue2 = rolldownRuntimeN(async () => {
    appInitialAvatarOverlayCompositionSurfaceIndexIndex9fQ9wihuIndexBFCcxPM5MapboxGlDCh0na97mS();
    await appInitialAvatarOverlayCompositionSurfaceIndexIndex9fQ9wihuIndexBFCcxPM5MapboxGlDCh0na97mO(
      () => import("../rpc"),
      __vite__mapDeps([0, 1, 2, 3, 4, 5]),
      import.meta.url,
    );
    await appInitialAvatarOverlayCompositionSurfaceIndexIndex9fQ9wihuIndexBFCcxPM5MapboxGlDCh0na97mO(
      () => import("../app-main-current"),
      __vite__mapDeps([
        6, 2, 3, 4, 1, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
        39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
        75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
        93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
        109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
        123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,
        137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
        151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
        165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
        179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
        193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206,
        207, 208, 209,
      ]),
      import.meta.url,
    );
  });
await rolldownRuntimeN(async () => {
  ModulepreloadPolyfill();
  indexValue1();
  await indexValue2();
})();
