// Restored from ref/webview/assets/document-BBd76VzF.js
// Current oaiproto.coworker.document schema backed by the verified semantic entry.
import {
  Artifact,
  ArtifactType,
  ColumnLayout,
  Comment,
  CommentReference,
  Document,
  DocumentGrid,
  DocumentSection,
  DocumentSettings,
  EmbeddedFont,
  EmbeddedFontType,
  Endnote,
  FontDefinition,
  Footnote,
  HeaderFooterContent,
  NoteProperties,
  NumberingDefinition,
  NumberingLevel,
  PageMargin,
  PageSetup,
  ParagraphNumbering,
  Playground,
  SectionBreakType,
  protobufPackage,
} from "../../../vendor/document-schema-entry-current";
function initDocumentSchema(): void {}
export {
  SectionBreakType,
  Playground,
  protobufPackage,
  NumberingDefinition,
  CommentReference,
  PageSetup,
  DocumentSection,
  EmbeddedFontType,
  Endnote,
  NoteProperties,
  HeaderFooterContent,
  Comment,
  DocumentSettings,
  Footnote,
  ArtifactType,
  Document,
  FontDefinition,
  ColumnLayout,
  DocumentGrid,
  Artifact,
  EmbeddedFont,
  NumberingLevel,
  initDocumentSchema,
  ParagraphNumbering,
  PageMargin,
};
