// Restored from ref/webview/assets/chunk-K5T4RW27-DBsaZQmV.js
// Current-build entry reusing the byte-identical prior semantic module.
import {
  initMermaidParserRuntime,
  createDefaultSharedCoreModule,
  NodeFileSystem,
  GitGraphGeneratedModule,
  inject,
  PacketGeneratedModule,
  TreeViewGeneratedModule,
  TreemapGeneratedModule,
  initParserServices,
  initNodeFileSystem,
  CommonValueConverter,
  PieGeneratedModule,
  setFunctionName,
  AbstractMermaidValueConverter,
  InfoGeneratedModule,
  WardleyGeneratedModule,
  ArchitectureGeneratedModule,
  MermaidGeneratedSharedModule,
  AbstractMermaidTokenBuilder,
  RadarGeneratedModule,
  initGeneratedGrammars,
  createDefaultCoreModule,
  initLangiumCore,
} from "../../package-adapters/mermaid-parser-current";
export {
  initMermaidParserRuntime,
  createDefaultSharedCoreModule,
  NodeFileSystem,
  GitGraphGeneratedModule,
  inject,
  PacketGeneratedModule,
  TreeViewGeneratedModule,
  TreemapGeneratedModule,
  initParserServices,
  initNodeFileSystem,
  CommonValueConverter,
  PieGeneratedModule,
  setFunctionName,
  AbstractMermaidValueConverter,
  InfoGeneratedModule,
  WardleyGeneratedModule,
  ArchitectureGeneratedModule,
  MermaidGeneratedSharedModule,
  AbstractMermaidTokenBuilder,
  RadarGeneratedModule,
  initGeneratedGrammars,
  createDefaultCoreModule,
  initLangiumCore,
};
