// Restored from ref/webview/assets/chunk-FPAJGGOC-CN4fXTF-.js
// Current-build entry reusing the byte-identical prior semantic module.
import {
  initLegacyMermaidParser,
  GitGraphGeneratedModule,
  createDefaultSharedModule,
  PacketGeneratedModule,
  TreemapGeneratedModule,
  setFunctionName,
  initParserServices,
  NodeFileSystem,
  CommonValueConverter,
  PieGeneratedModule,
  initNodeFileSystem,
  AbstractMermaidValueConverter,
  InfoGeneratedModule,
  initGeneratedGrammars,
  ArchitectureGeneratedModule,
  MermaidGeneratedSharedModule,
  AbstractMermaidTokenBuilder,
  RadarGeneratedModule,
  inject,
  initLangiumCore,
  createDefaultCoreModule,
} from "../../package-adapters/mermaid-parser-legacy";
export {
  initLegacyMermaidParser,
  GitGraphGeneratedModule,
  createDefaultSharedModule,
  PacketGeneratedModule,
  TreemapGeneratedModule,
  setFunctionName,
  initParserServices,
  NodeFileSystem,
  CommonValueConverter,
  PieGeneratedModule,
  initNodeFileSystem,
  AbstractMermaidValueConverter,
  InfoGeneratedModule,
  initGeneratedGrammars,
  ArchitectureGeneratedModule,
  MermaidGeneratedSharedModule,
  AbstractMermaidTokenBuilder,
  RadarGeneratedModule,
  inject,
  initLangiumCore,
  createDefaultCoreModule,
};
