// Restored from ref/webview/assets/conversation-markdown-BjFKV53f.js
// Boundary facade for conversation markdown rendering and formatting helpers.
import {
  aD as formatShellCommand,
  bF as initPathHelpers,
  DL as normalizeWorkspacePath,
  Gv as initMarkdownNormalizationRuntime,
  iD as initCommandMarkdownRuntime,
  Kg as initNormalizedPathUtilities,
  kj as normalizeConfigPath,
  Oj as normalizeArtifactPathKey,
  qg as resolveProjectlessResourcePath,
  Tj as isAbsolutePath,
  Vv as initMarkdownContentRuntime,
  Wv as rewriteMarkdownResourceLinks,
  wj as initArtifactPreviewRuntime,
  zv as renderChangeAsUnifiedDiff,
} from "../vendor/appg-thread-shared-runtime";
import {
  Ba as groupClosedActivityUnits,
  dt as initPersonalityChangedItems,
  Et as isConversationItemInProgress,
  ft as resolveRenderableAgentItems,
  Ha as initPostAssistantItemGrouping,
  La as shouldRenderCollapsedActivityDetails,
  lt as initRenderableOutputGrouping,
  Ra as closeActivitySlices,
  Tt as initRemoteTaskCreatedItems,
  ut as getTurnAgentItemGroups,
  Va as collectRenderableAgentUnits,
  za as wrapActivityUnits,
} from "../vendor/profile-page-runtime";

export {
  closeActivitySlices,
  collectRenderableAgentUnits,
  formatShellCommand,
  getTurnAgentItemGroups,
  groupClosedActivityUnits,
  initArtifactPreviewRuntime,
  initCommandMarkdownRuntime,
  initMarkdownContentRuntime,
  initMarkdownNormalizationRuntime,
  initNormalizedPathUtilities,
  initPathHelpers,
  initPersonalityChangedItems,
  initPostAssistantItemGrouping,
  initRemoteTaskCreatedItems,
  initRenderableOutputGrouping,
  isAbsolutePath,
  isConversationItemInProgress,
  normalizeArtifactPathKey,
  normalizeConfigPath,
  normalizeWorkspacePath,
  renderChangeAsUnifiedDiff,
  resolveProjectlessResourcePath,
  resolveRenderableAgentItems,
  rewriteMarkdownResourceLinks,
  shouldRenderCollapsedActivityDetails,
  wrapActivityUnits,
};
