// Restored from ref/webview/assets/app-initial~app-main~worktree-init-v2-page~appgen-publication-terms-route~remote-conversati~oykv7gy7-B4ar2dlW.js
// Boundary facade for appgen publication-terms resource opening and panel tabs.
import {
  $N as initVscodeApiBridge,
  a_ as initFileTypeDetectionHelpers,
  Aj as resolveWorkspacePathFromCwd,
  CS as initOpenFileOutcomeEventRuntime,
  DE as openFileOutcomeEvent,
  F_ as readRouteScopeValue,
  i_ as getPathExtension,
  kL as readFileContentSampleByteLimit,
  MD as renderMcpCapabilityIcon,
  o_ as isMarkdownPreviewPath,
  r_ as getImagePreviewDisplayMode,
  Sj as getPathBasename,
  s_ as isPdfPreviewPath,
  TS as logScopedProductEvent,
  UR as isAbsoluteOrWindowsPath,
  wj as initArtifactPreviewRuntime,
  xL as isRemoteHostConfig,
  YN as sendHostRequest,
  yR as isUrlLikePath,
} from "../vendor/appg-thread-shared-runtime";
import {
  _c as getSidePanelController,
  bc as activateSidePanelPlacement,
  dn as createReadFileContents,
  Kr as openArtifactPanelTab,
  mc as sidePanelPlacements,
  pn as mcpCapabilityPanelTab,
  ti as getWorkspaceFilePanelTabSource,
  vc as getPanelTabPlacement,
  Yt as openWorkspaceFilePanelTab,
} from "../vendor/projects-app-shared-runtime";

export {
  activateSidePanelPlacement,
  createReadFileContents,
  getImagePreviewDisplayMode,
  getPanelTabPlacement,
  getPathBasename,
  getPathExtension,
  getSidePanelController,
  getWorkspaceFilePanelTabSource,
  initArtifactPreviewRuntime,
  initFileTypeDetectionHelpers,
  initOpenFileOutcomeEventRuntime,
  initVscodeApiBridge,
  isAbsoluteOrWindowsPath,
  isMarkdownPreviewPath,
  isPdfPreviewPath,
  isRemoteHostConfig,
  isUrlLikePath,
  logScopedProductEvent,
  mcpCapabilityPanelTab,
  openArtifactPanelTab,
  openFileOutcomeEvent,
  openWorkspaceFilePanelTab,
  readFileContentSampleByteLimit,
  readRouteScopeValue,
  renderMcpCapabilityIcon,
  resolveWorkspacePathFromCwd,
  sendHostRequest,
  sidePanelPlacements,
};
