// Restored from ref/webview/assets/use-element-in-view-CZGmoMvk.js
// Boundary facade for shared utility hooks, small icons, and vendored helpers.
import {
  $P as initAppScope,
  AB as initScopeRuntime,
  BV as getJsxRuntime,
  cV as createSymbolConstructor,
  Iw as onboardingWizardAction,
  JB as createIsIndex,
  JV as initReactRuntime,
  jM as initPersistentSignalRuntime,
  kE as initProductEventRuntime,
  MM as createPersistentSignal,
  nV as createArrayPush,
  oV as createIsObject,
  qV as getChunkModuleExports,
  tV as createIsArray,
  uV as createEq,
  Uf as initHostWorkspaceQueries,
  ub as initOnboardingWizardTrackingRuntime,
  VB as createIsArrayLike,
  VP as initClassNameRuntime,
  wA as createIdentity,
  XB as createIsArguments,
  _r as createDefineProperty,
  _u as createBaseAt,
} from "../vendor/appg-thread-shared-runtime";

export {
  createArrayPush,
  createBaseAt,
  createDefineProperty,
  createEq,
  createIdentity,
  createIsArguments,
  createIsArray,
  createIsArrayLike,
  createIsIndex,
  createIsObject,
  createPersistentSignal,
  createSymbolConstructor,
  getChunkModuleExports,
  getJsxRuntime,
  initAppScope,
  initClassNameRuntime,
  initHostWorkspaceQueries,
  initOnboardingWizardTrackingRuntime,
  initPersistentSignalRuntime,
  initProductEventRuntime,
  initReactRuntime,
  initScopeRuntime,
  onboardingWizardAction,
};
