// Restored from ref/webview/assets/local-conversation-page-D7JrTtqP.js
// Local conversation page container runtime bindings and side-effect helpers.
import {
  $N as initVscodeApiBridge,
  $P as initAppScope,
  AB as initScopeRuntime,
  AV as initReactQueryRuntime,
  A_ as appShellTabIds,
  DL as normalizeWorkspacePath,
  Em as conversationTurnsSignal,
  FB as useScope,
  Gp as conversationReasoningEffortSignal,
  Hp as lastTurnCwdSignal,
  IB as useSignalValue,
  I_ as initRouteScope,
  Io as initConnectorAppsListQuery,
  Ip as localResponseInProgressSignal,
  JV as initReactRuntime,
  M_ as localConversationRouteScope,
  O_ as initConversationRouteSourceHelpers,
  PB as useScopedValue,
  QP as appScope,
  Rn as useCommandRegistration,
  Rp as appServerNotificationSignal,
  SP as initMotionRuntime,
  T_ as getRouteConversationId,
  Tp as hasConversationSignal,
  VE as initGlobalStateQueryRuntime,
  Wp as conversationModelSignal,
  Xp as latestConversationTurnSignal,
  Vp as lastTurnDiffSignal,
  ak as initAppServerRequestBridge,
  bF as initIntlMessageRuntime,
  cm as conversationHostIdSignal,
  cv as sourceWorkspaceRootAfterRestoreSignal,
  dV as createDerivedSignal,
  gm as backgroundAgentSnapshotSignal,
  gp as conversationCwdSignal,
  jm as conversationModeSignal,
  kj as normalizeConfigPath,
  li as ProjectAvatar,
  lm as conversationResumeStateSignal,
  mv as initCurrentRefViewRuntime,
  ok as sendAppServerRequest,
  pz as toConversationId,
  qV as getChunkModuleExports,
  qj as useStatsigGate,
  sm as conversationRequestsSignal,
  sv as pendingProjectlessLocalConversationSignal,
  um as rolloutPathSignal,
  vm as subagentParentThreadIdSignal,
  yv as Navigate,
  zo as useAppsQuery,
} from "../vendor/appg-thread-shared-runtime";
import {
  Sl as activeWorkspaceDiffSignal,
  nc as appShellIntlSignal,
  $r as clearRestoredWorkspaceRoot,
  fl as reviewSourceSignal,
  hl as resetReviewSource,
  Vn as initProjectsAppSharedRuntime,
  Gl as localConversationTitleSignal,
  ml as shouldRestoreReviewStateSignal,
  Kr as openWorkspaceDiffPanelTab,
  Yt as openWorkspaceFilePanelTab,
  pd as setRightPanelFullWidth,
  Tr as pendingClientLocalConversationSignal,
  pl as reviewSourceWorkspaceRootSignal,
  rd as rightPanelVisibleSignal,
  Yl as rightPanelController,
  nd as rightPanelOpenSignal,
  ql as rightPanelTabController,
  j as selectedSummaryPanelSignal,
  N as setSelectedSummarySource,
  md as summaryPanelPinnedSignal,
  Ll as targetWorkspaceRootSignal,
  Bn as ThreadAppShellLayout,
  ul as setReviewSourceFromLastTurn,
  zc as reviewPaneSnapshotMetricsSignal,
  zl as activeHostIdSignal,
} from "../vendor/projects-app-shared-runtime";
import {
  AutomationTooltipSurface,
  ComposerDismissableLayer,
  initAutomationSurface,
} from "../automation/automation-surface";
import {
  clearSelectedSummarySource,
  getRenderableTurnItems,
  getTurnAgentItemGroups,
  isConversationItemInProgress,
  LocalConversationTurnRow,
  resolveRenderableAgentItems,
  WorkedForCollapsedAgentsLabel,
} from "./local-conversation-profile-runtime";
import {
  getProjectAppearance,
  initProjectAppearanceChunk,
} from "../projects/project-appearance";
import {
  AppgenProjectHeader,
  initAppgenProjectHeaderChunk,
} from "../appgen/project-header";
import {
  createDebugPanelSourceId,
  getEditedFilesFromTurns,
  getReferencedFilesFromTurns,
  initDebugPanelRuntime,
  initDebugPanelSourceRuntime,
  registerDebugPanelSource,
  unregisterDebugPanelSource,
  useIsDebugPanelEnabled,
} from "../debug/debug-panel";
import {
  initPendingWorktreeChunk,
  PendingWorktreeConversation,
} from "../worktree/pending-worktree-conversation-ui";
import {
  focusPendingReviewPanelTarget,
  initPullRequestThreadActionsChunk,
  openInitialReviewPanelTarget,
  pendingReviewPanelTargetSignal,
  resetReviewPanelEmptyState,
  revealChangedFilesInReviewPanel,
  scheduleReviewRestore,
  shouldExpandReviewPanelSignal,
  syncReviewPanelForRestoredSource,
} from "./pull-request-review-panel-actions";

export {
  activeHostIdSignal,
  activeWorkspaceDiffSignal,
  appScope,
  appServerNotificationSignal,
  appShellIntlSignal,
  appShellTabIds,
  AppgenProjectHeader,
  AutomationTooltipSurface,
  backgroundAgentSnapshotSignal,
  clearRestoredWorkspaceRoot,
  clearSelectedSummarySource,
  ComposerDismissableLayer,
  conversationCwdSignal,
  conversationHostIdSignal,
  conversationModeSignal,
  conversationModelSignal,
  conversationReasoningEffortSignal,
  conversationRequestsSignal,
  conversationResumeStateSignal,
  conversationTurnsSignal,
  createDebugPanelSourceId,
  createDerivedSignal,
  focusPendingReviewPanelTarget,
  getChunkModuleExports,
  getEditedFilesFromTurns,
  getProjectAppearance,
  getReferencedFilesFromTurns,
  getRenderableTurnItems,
  getRouteConversationId,
  getTurnAgentItemGroups,
  hasConversationSignal,
  initAppScope,
  initAppgenProjectHeaderChunk,
  initAppServerRequestBridge,
  initAutomationSurface,
  initConnectorAppsListQuery,
  initConversationRouteSourceHelpers,
  initCurrentRefViewRuntime,
  initDebugPanelRuntime,
  initDebugPanelSourceRuntime,
  initGlobalStateQueryRuntime,
  initIntlMessageRuntime,
  initMotionRuntime,
  initPendingWorktreeChunk,
  initProjectAppearanceChunk,
  initProjectsAppSharedRuntime,
  initPullRequestThreadActionsChunk,
  initReactQueryRuntime,
  initReactRuntime,
  initRouteScope,
  initScopeRuntime,
  initVscodeApiBridge,
  isConversationItemInProgress,
  lastTurnCwdSignal,
  lastTurnDiffSignal,
  latestConversationTurnSignal,
  localConversationRouteScope,
  localConversationTitleSignal,
  localResponseInProgressSignal,
  LocalConversationTurnRow,
  Navigate,
  normalizeConfigPath,
  normalizeWorkspacePath,
  openInitialReviewPanelTarget,
  openWorkspaceDiffPanelTab,
  openWorkspaceFilePanelTab,
  pendingClientLocalConversationSignal,
  pendingProjectlessLocalConversationSignal,
  pendingReviewPanelTargetSignal,
  PendingWorktreeConversation,
  ProjectAvatar,
  registerDebugPanelSource,
  resetReviewPanelEmptyState,
  resetReviewSource,
  resolveRenderableAgentItems,
  revealChangedFilesInReviewPanel,
  reviewPaneSnapshotMetricsSignal,
  reviewSourceSignal,
  reviewSourceWorkspaceRootSignal,
  rightPanelController,
  rightPanelOpenSignal,
  rightPanelTabController,
  rightPanelVisibleSignal,
  rolloutPathSignal,
  scheduleReviewRestore,
  selectedSummaryPanelSignal,
  sendAppServerRequest,
  setReviewSourceFromLastTurn,
  setRightPanelFullWidth,
  setSelectedSummarySource,
  shouldExpandReviewPanelSignal,
  shouldRestoreReviewStateSignal,
  sourceWorkspaceRootAfterRestoreSignal,
  subagentParentThreadIdSignal,
  summaryPanelPinnedSignal,
  syncReviewPanelForRestoredSource,
  targetWorkspaceRootSignal,
  ThreadAppShellLayout,
  toConversationId,
  unregisterDebugPanelSource,
  useAppsQuery,
  useCommandRegistration,
  useIsDebugPanelEnabled,
  useScope,
  useScopedValue,
  useSignalValue,
  useStatsigGate,
  WorkedForCollapsedAgentsLabel,
};
