// Restored from ref/webview/assets/local-conversation-stream-role-product-event-DHQpO55W.js
// Runtime bindings for local conversation stream-role and heartbeat host events.
import {
  $P as initAppScope,
  AB as initScopeRuntime,
  cP as initVscodeMessageBridge,
  FB as useScope,
  gE as streamRoleProductEvent,
  Gj as initStatsigFeatureGateHooks,
  IB as useSignalValue,
  JV as initReactRuntime,
  kE as initProductEventRuntime,
  lP as vscodeMessageBridge,
  PB as useScopedValue,
  QP as appScope,
  qV as getChunkModuleExports,
  qj as useStatsigGate,
} from "../vendor/appg-thread-shared-runtime";
import {
  CS as initThreadStateSignalRuntime,
  I_ as initRouteScope,
  Jp as conversationPermissionConfigSignal,
  M_ as localConversationRouteScope,
  Op as initConversationStateSelectors,
  TS as setProductEventProperties,
  Up as conversationCollaborationModeSignal,
  Xp as latestConversationTurnSignal,
  _m as conversationStreamRoleSignal,
} from "../vendor/projects-app-shared-runtime";

export {
  appScope,
  conversationCollaborationModeSignal,
  conversationPermissionConfigSignal,
  conversationStreamRoleSignal,
  getChunkModuleExports,
  initAppScope,
  initConversationStateSelectors,
  initProductEventRuntime,
  initReactRuntime,
  initRouteScope,
  initScopeRuntime,
  initStatsigFeatureGateHooks,
  initThreadStateSignalRuntime,
  initVscodeMessageBridge,
  latestConversationTurnSignal,
  localConversationRouteScope,
  setProductEventProperties,
  streamRoleProductEvent,
  useScope,
  useScopedValue,
  useSignalValue,
  useStatsigGate,
  vscodeMessageBridge,
};
