// Restored from ref/webview/assets/use-host-config-CiYpjHRj.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 133 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const useHostConfigTn: any;
export declare const useHostConfigCn: any;
export declare const useHostConfigWn: any;
export declare const useHostConfigLn: any;
export declare const useHostConfigPn: any;
export declare const useHostConfigFn: any;
export declare const useHostConfigDn: any;
export declare const useHostConfigN: any;
export declare const _useHostConfigSn: any;
export declare const _useHostConfigTn: any;
export declare const useHostConfigRn: any;
export declare const useHostConfigNn: any;
export declare const useHostConfigIn: any;
export declare const useHostConfigEn: any;
export declare const useHostConfigAn: any;
export declare const useHostConfigGt: any;
export declare const useHostConfigWt: any;
export declare const useHostConfigKt: any;
export declare const useHostConfigNt: any;
export declare const _useHostConfigZt: any;
export declare const useHostConfigPt: any;
export declare const _useHostConfigWt: any;
export declare const useHostConfigTt: any;
export declare const useHostConfigDt: any;
export declare const useHostConfigMt: any;
export declare const useHostConfigCt: any;
export declare const _useHostConfigBt: any;
export declare const _useHostConfigYt: any;
export declare const _useHostConfigCt: any;
export declare const _useHostConfigOt: any;
export declare const _useHostConfigRt: any;
export declare const _useHostConfigNt: any;
export declare const _useHostConfigTt: any;
export declare const _useHostConfigEt: any;
export declare const useHostConfigX: any;
export declare const useHostConfigZ: any;
export declare const useHostConfigU: any;
export declare const useHostConfigH: any;
export declare const useHostConfigG: any;
export declare const useHostConfigM: any;
export declare const useHostConfigR: any;
export declare const _useHostConfigJ: any;
export declare const useHostConfigI: any;
export declare const _useHostConfigK: any;
export declare const __useHostConfigT: any;
export declare const useHostConfigO: any;
export declare const useHostConfigS: any;
export declare const _useHostConfigW: any;
export declare const useHostConfigC: any;
export declare const _useHostConfigV: any;
export declare const useHostConfigUnderscore: any;
export declare const _useHostConfigH: any;
export declare const _useHostConfigM: any;
export declare const _useHostConfigU: any;
export declare const _useHostConfigL: any;
export declare const _useHostConfigS: any;
export declare const _useHostConfigI: any;
export declare const __useHostConfigN: any;
export declare const $: any;
export declare const $t: any;
export declare const useHostConfigA: any;
export declare const useHostConfigAt: any;
export declare const useHostConfigB: any;
export declare const useHostConfigBt: any;
export declare const useHostConfigD: any;
export declare const useHostConfigE: any;
export declare const useHostConfigEt: any;
export declare const useHostConfigF: any;
export declare const useHostConfigFt: any;
export declare const useHostConfigHt: any;
export declare const useHostConfigIt: any;
export declare const useHostConfigJ: any;
export declare const useHostConfigJt: any;
export declare const useHostConfigK: any;
export declare const useHostConfigL: any;
export declare const useHostConfigLt: any;
export declare const _useHostConfigN: any;
export declare const useHostConfigOt: any;
export declare const useHostConfigP: any;
export declare const useHostConfigQ: any;
export declare const useHostConfigQt: any;
export declare const useHostConfigRt: any;
export declare const useHostConfigSn: any;
export declare const useHostConfigSt: any;
export declare const useHostConfigUt: any;
export declare const useHostConfigV: any;
export declare const useHostConfigVt: any;
export declare const useHostConfigW: any;
export declare const useHostConfigXt: any;
export declare const useHostConfigY: any;
export declare const useHostConfigYt: any;
export declare const useHostConfigZt: any;
export declare const _t: any;
export declare const _useHostConfigA: any;
export declare const at: any;
export declare const _useHostConfigB: any;
export declare const useHostConfigBn: any;
export declare const _useHostConfigC: any;
export declare const _useHostConfigCn: any;
export declare const _useHostConfigD: any;
export declare const _useHostConfigDt: any;
export declare const _useHostConfigF: any;
export declare const _useHostConfigFt: any;
export declare const _useHostConfigG: any;
export declare const useHostConfigGn: any;
export declare const _useHostConfigGt: any;
export declare const useHostConfigHn: any;
export declare const _useHostConfigHt: any;
export declare const _useHostConfigIt: any;
export declare const _useHostConfigJt: any;
export declare const _useHostConfigKt: any;
export declare const _useHostConfigLt: any;
export declare const useHostConfigMn: any;
export function _useHostConfigMt(
  hostConfigs: Array<{ id?: string; hostId?: string }> | null | undefined,
  hostId: string | null | undefined,
): unknown {
  if (hostId == null) return null;
  return (
    hostConfigs?.find((hostConfig) => {
      return hostConfig.id === hostId || hostConfig.hostId === hostId;
    }) ?? null
  );
}
export declare const _useHostConfigO: any;
export declare const on: any;
export declare const _useHostConfigP: any;
export declare const _useHostConfigPt: any;
export declare const _useHostConfigQ: any;
export declare const _useHostConfigQt: any;
export declare const _useHostConfigR: any;
export declare const _useHostConfigSt: any;
export declare const ___useHostConfigT: any;
export declare const useHostConfigUn: any;
export declare const _useHostConfigUt: any;
export declare const useHostConfigVn: any;
export declare const _useHostConfigVt: any;
export declare const _useHostConfigX: any;
export declare const useHostConfigXn: any;
export declare const _useHostConfigXt: any;
export declare const _useHostConfigY: any;
export declare const useHostConfigYn: any;

export declare const sendAppServerRequest: any;
export declare const formatGoalObjectiveInput: any;
export declare const useRemoteHostConnections: any;
export declare const useHostConfigById: any;
export declare const isBrowserCommentAttachment: any;
export const LOCAL_HOST_ID = "local";
export declare const _useHostConfigZ: any;
export declare const getLatestTurn: any;
export declare const getLatestWaitingRequest: any;
export declare const getThreadTitle: any;
export declare const getThreadTurnCount: any;
export declare const getThreadTurns: any;
export declare const hasWaitingApprovalRequest: any;
export declare const isSubAgentThread: any;
export declare const shouldHideSubAgentThread: any;
export declare const markdownToSearchText: any;
export declare const parseHeartbeatMessage: any;
export declare const infiniteQueryBehavior: any;
export declare const getConversationPromptTitle: any;
export declare const getConversationTitleFromSnapshot: any;
export declare const useSharedObjectState: any;
export declare function getWorkspaceRelativePath(
  filePath: string,
  workspaceRoot?: string | null,
): string;
