// Restored from ref/webview/assets/chunk-ABZYJK2D-C7_WFFRt.js
// Legacy Mermaid common-runtime surface backed by the restored vendor runtime.
import {
  UnknownDiagramError,
  addDirective,
  assignWithDepth_default as assignWithDepth,
  calculateMathMLDimensions,
  clear as clearCommonDb,
  common_default as commonUtils,
  commonDb_exports as commonDb,
  configureSvgSize,
  defaultConfig,
  detectType,
  detectors as diagramDetectors,
  directiveRegex,
  evaluate,
  frontMatterRegex,
  getAccDescription,
  getAccTitle,
  getConfig,
  getConfig2 as getConfigAlias,
  getDiagram,
  getDiagramLoader,
  getDiagramTitle,
  getSiteConfig,
  getThemeVariables,
  getUrl,
  getUserDefinedConfig,
  hasKatex,
  lineBreakRegex,
  parseGenericTypes,
  registerDiagram,
  registerLazyLoadedDiagrams,
  renderKatexSanitized,
  reset as resetConfig,
  sanitizeDirective,
  sanitizeText as sanitizeTextWithConfig,
  sanitizeText2,
  saveConfigFromInitialize,
  setAccDescription,
  setAccTitle,
  setConfig,
  setDiagramTitle,
  setSiteConfig,
  setupGraphViewbox,
  setupGraphViewbox2 as setupGraphViewboxAlias,
  styles_default as getStyles,
  themes_default as themeRegistry,
  updateSiteConfig,
} from "mermaid/dist/chunks/mermaid.core/chunk-ABZYJK2D.mjs";
const sanitizeHtml = sanitizeText2;
const sanitizeText = sanitizeText2;
const defaultConfigFrozen = Object.freeze(defaultConfig);
const setConfigAlias = setConfig;
function initDomPurifyRuntime(): void {}
function initLegacyMermaidCommonRuntime(): void {}
export {
  lineBreakRegex,
  setAccDescription,
  getDiagramTitle,
  getUserDefinedConfig,
  getUrl,
  resetConfig,
  setSiteConfig,
  setConfig,
  sanitizeDirective,
  getStyles,
  setupGraphViewbox,
  sanitizeTextWithConfig,
  registerDiagram,
  registerLazyLoadedDiagrams,
  hasKatex,
  renderKatexSanitized,
  sanitizeHtml,
  sanitizeText,
  getDiagramLoader,
  getThemeVariables,
  setConfigAlias,
  setAccTitle,
  setDiagramTitle,
  updateSiteConfig,
  themeRegistry,
  initDomPurifyRuntime,
  getAccDescription,
  clearCommonDb,
  getConfig,
  configureSvgSize,
  defaultConfig,
  detectType,
  frontMatterRegex,
  evaluate,
  calculateMathMLDimensions,
  parseGenericTypes,
  initLegacyMermaidCommonRuntime,
  defaultConfigFrozen,
  directiveRegex,
  addDirective,
  commonDb,
  diagramDetectors,
  setupGraphViewboxAlias,
  assignWithDepth,
  commonUtils,
  UnknownDiagramError,
  defaultConfigFrozen as defaultConfigAlias,
  getAccTitle,
  getSiteConfig,
  getDiagram,
  getConfigAlias,
  saveConfigFromInitialize,
};
