// Restored from ref/webview/assets/remote-text-edit-session-0olsg5KH.js
// Complete current-ref compatibility export surface for remoteTextEditSessionCurrent.

// Stable aliases for the current remote text edit session exports.
// prettier-ignore
export {
  $ as remoteTextEditSessionDollarExport, A as remoteTextEditSessionUpperAExport, B as remoteTextEditSessionUpperBExport, C as remoteTextEditSessionUpperCExport,
  D as remoteTextEditSessionUpperDExport, E as remoteTextEditSessionUpperEExport, F as remoteTextEditSessionUpperFExport, G as remoteTextEditSessionUpperGExport,
  H as remoteTextEditSessionUpperHExport, I as remoteTextEditSessionUpperIExport, J as remoteTextEditSessionUpperJExport, K as remoteTextEditSessionUpperKExport,
  L as remoteTextEditSessionUpperLExport, M as remoteTextEditSessionUpperMExport, N as remoteTextEditSessionUpperNExport, O as remoteTextEditSessionUpperOExport,
  P as remoteTextEditSessionUpperPExport, Q as remoteTextEditSessionUpperQExport, R as remoteTextEditSessionUpperRExport, S as remoteTextEditSessionUpperSExport,
  T as remoteTextEditSessionUpperTExport, U as remoteTextEditSessionUpperUExport, V as remoteTextEditSessionUpperVExport, W as remoteTextEditSessionUpperWExport,
  X as remoteTextEditSessionUpperXExport, Y as remoteTextEditSessionUpperYExport, Z as remoteTextEditSessionUpperZExport, _ as remoteTextEditSessionUnderscoreExport,
  a as remoteTextEditSessionLowerAExport, b as remoteTextEditSessionLowerBExport, c as remoteTextEditSessionLowerCExport, d as remoteTextEditSessionLowerDExport,
  et as remoteTextEditSessionLowerELowerTExport, f as remoteTextEditSessionLowerFExport, g as remoteTextEditSessionLowerGExport, h as remoteTextEditSessionLowerHExport,
  i as remoteTextEditSessionLowerIExport, j as remoteTextEditSessionLowerJExport, k as remoteTextEditSessionLowerKExport, l as remoteTextEditSessionLowerLExport,
  m as remoteTextEditSessionLowerMExport, n as remoteTextEditSessionLowerNExport, o as remoteTextEditSessionLowerOExport, p as remoteTextEditSessionLowerPExport,
  q as remoteTextEditSessionLowerQExport, r as remoteTextEditSessionLowerRExport, s as remoteTextEditSessionLowerSExport, t as remoteTextEditSessionLowerTExport,
  u as remoteTextEditSessionLowerUExport, v as remoteTextEditSessionLowerVExport, w as remoteTextEditSessionLowerWExport, x as remoteTextEditSessionLowerXExport,
  y as remoteTextEditSessionLowerYExport, z as remoteTextEditSessionLowerZExport
} from "../../vendor/remote-text-edit-session-current-bundle";

// prettier-ignore
export { $ as remoteTextEditSessionCurrentCompatSlotDollar, A as remoteTextEditSessionCurrentCompatSlotUpperA, B as remoteTextEditSessionCurrentCompatSlotUpperB, C as remoteTextEditSessionCurrentCompatSlotUpperC, D as remoteTextEditSessionCurrentCompatSlotUpperD, E as remoteTextEditSessionCurrentCompatSlotUpperE, F as remoteTextEditSessionCurrentCompatSlotUpperF, G as remoteTextEditSessionCurrentCompatSlotUpperG, H as remoteTextEditSessionCurrentCompatSlotUpperH, I as remoteTextEditSessionCurrentCompatSlotUpperI, J as remoteTextEditSessionCurrentCompatSlotUpperJ, K as remoteTextEditSessionCurrentCompatSlotUpperK, L as remoteTextEditSessionCurrentCompatSlotUpperL, M as remoteTextEditSessionCurrentCompatSlotUpperM, N as remoteTextEditSessionCurrentCompatSlotUpperN, O as remoteTextEditSessionCurrentCompatSlotUpperO, P as remoteTextEditSessionCurrentCompatSlotUpperP, Q as remoteTextEditSessionCurrentCompatSlotUpperQ, R as remoteTextEditSessionCurrentCompatSlotUpperR, S as remoteTextEditSessionCurrentCompatSlotUpperS, T as remoteTextEditSessionCurrentCompatSlotUpperT, U as remoteTextEditSessionCurrentCompatSlotUpperU, V as remoteTextEditSessionCurrentCompatSlotUpperV, W as remoteTextEditSessionCurrentCompatSlotUpperW, X as remoteTextEditSessionCurrentCompatSlotUpperX, Y as remoteTextEditSessionCurrentCompatSlotUpperY, Z as remoteTextEditSessionCurrentCompatSlotUpperZ, _ as remoteTextEditSessionCurrentCompatSlotUnderscore, a as remoteTextEditSessionCurrentCompatSlotLowerA, b as remoteTextEditSessionCurrentCompatSlotLowerB, c as remoteTextEditSessionCurrentCompatSlotLowerC, d as remoteTextEditSessionCurrentCompatSlotLowerD, et as remoteTextEditSessionCurrentCompatSlotLowerELowerT, f as remoteTextEditSessionCurrentCompatSlotLowerF, g as remoteTextEditSessionCurrentCompatSlotLowerG, h as remoteTextEditSessionCurrentCompatSlotLowerH, i as remoteTextEditSessionCurrentCompatSlotLowerI, j as remoteTextEditSessionCurrentCompatSlotLowerJ, k as remoteTextEditSessionCurrentCompatSlotLowerK, l as remoteTextEditSessionCurrentCompatSlotLowerL, m as remoteTextEditSessionCurrentCompatSlotLowerM, n as remoteTextEditSessionCurrentCompatSlotLowerN, o as remoteTextEditSessionCurrentCompatSlotLowerO, p as remoteTextEditSessionCurrentCompatSlotLowerP, q as remoteTextEditSessionCurrentCompatSlotLowerQ, r as remoteTextEditSessionCurrentCompatSlotLowerR, s as remoteTextEditSessionCurrentCompatSlotLowerS, t as remoteTextEditSessionCurrentCompatSlotLowerT, u as remoteTextEditSessionCurrentCompatSlotLowerU, v as remoteTextEditSessionCurrentCompatSlotLowerV, w as remoteTextEditSessionCurrentCompatSlotLowerW, x as remoteTextEditSessionCurrentCompatSlotLowerX, y as remoteTextEditSessionCurrentCompatSlotLowerY, z as remoteTextEditSessionCurrentCompatSlotLowerZ } from "../../vendor/remote-text-edit-session-current-bundle";
