// Restored from ref/webview/assets/browser-use-settings-CsWPz1kU.js
// Current-build entry reusing the fingerprint-verified semantic module.
import {
  initializeBrowserUseSitePermissions,
  PasswordManagerSettingsRow,
  BrowserUseHistoryApprovalModeRow,
  initializeBrowserUseSettingsChunk,
  initializePreferredBrowserUsePluginHelpers,
  BrowserDomainListSection,
  initializePluginControlList,
  BrowsingHistorySettingsRow,
  BrowserUseSettings,
  PluginControlList,
  ContactInfoSettingsRow,
  SiteSettingsRow,
  findPreferredBrowserUsePlugin,
  ExtensionsSettingsRow,
  BrowserUseApprovalModeRow,
  ClearBrowsingDataRow,
  BrowserUseSettingsSections,
  FullCdpDeveloperModeSection,
  initializeFullCdpDeveloperModeSection,
} from "../../../browser/browser-use-settings";
export {
  initializeBrowserUseSitePermissions,
  PasswordManagerSettingsRow,
  BrowserUseHistoryApprovalModeRow,
  initializeBrowserUseSettingsChunk,
  initializePreferredBrowserUsePluginHelpers,
  BrowserDomainListSection,
  initializePluginControlList,
  BrowsingHistorySettingsRow,
  BrowserUseSettings,
  PluginControlList,
  ContactInfoSettingsRow,
  SiteSettingsRow,
  findPreferredBrowserUsePlugin,
  ExtensionsSettingsRow,
  BrowserUseApprovalModeRow,
  ClearBrowsingDataRow,
  BrowserUseSettingsSections,
  FullCdpDeveloperModeSection,
  initializeFullCdpDeveloperModeSection,
};
