// Restored from ref/webview/assets/chunk-ICPOFSXX-DR5eNcWR.js
// Current Mermaid common-runtime surface backed by the restored vendor runtime.
import {
  $ as sanitizeHtml,
  _chunkICPOFSXXA as clearCommonDb,
  _chunkICPOFSXXB as getConfig,
  _chunkICPOFSXXC as getDiagramTitle,
  _chunkICPOFSXXD as getUrl,
  _chunkICPOFSXXF as resetConfig,
  _chunkICPOFSXXG as setSiteConfig,
  _chunkICPOFSXXI as calculateMathMLDimensions,
  _chunkICPOFSXXJ as getStyles,
  _chunkICPOFSXXK as setupGraphViewbox,
  _chunkICPOFSXXL as sanitizeTextWithConfig,
  _chunkICPOFSXXM as registerDiagram,
  _chunkICPOFSXXN as addDirective,
  _chunkICPOFSXXO as commonDb,
  _chunkICPOFSXXP as renderKatexSanitized,
  _chunkICPOFSXXR as sanitizeText,
  _chunkICPOFSXXS as commonUtils,
  _chunkICPOFSXXT as getSiteConfig,
  _chunkICPOFSXXV as getAccTitle,
  _chunkICPOFSXXW as setDiagramTitle,
  _chunkICPOFSXXX as getDiagram,
  _chunkICPOFSXXZ as saveConfigFromInitialize,
  chunkICPOFSXXB as setAccDescription,
  chunkICPOFSXXC as configureSvgSize,
  chunkICPOFSXXD as defaultConfig,
  chunkICPOFSXXE as getThemeVariables,
  chunkICPOFSXXF as detectType,
  chunkICPOFSXXH as evaluate,
  chunkICPOFSXXI as sanitizeDirective,
  chunkICPOFSXXJ as parseGenericTypes,
  chunkICPOFSXXK as hasKatex,
  chunkICPOFSXXN as registerLazyLoadedDiagrams,
  chunkICPOFSXXO as getUserDefinedConfig,
  chunkICPOFSXXP as diagramDetectors,
  chunkICPOFSXXR as assignWithDepth,
  chunkICPOFSXXS as getDiagramLoader,
  chunkICPOFSXXU as setConfig,
  chunkICPOFSXXUnderscore as getAccDescription,
  chunkICPOFSXXV as setAccTitle,
  chunkICPOFSXXW as getEffectiveHtmlLabels,
  chunkICPOFSXXX as updateSiteConfig,
  chunkICPOFSXXY as themeRegistry,
  initChunkICPOFSXXCurrent,
  initChunkICPOFSXXDomPurifyRuntime,
} from "../../../vendor/chunk-icpofsxx";
const frontMatterRegex = /^-{3}\s*[\n\r](.*?)[\n\r]-{3}\s*[\n\r]+/s;
const directiveRegex =
  /%{2}{\s*(?:(\w+)\s*:|(\w+))\s*(?:(\w+)|((?:(?!}%{2}).|\r?\n)*))?\s*(?:}%{2})?/gi;
const lineBreakRegex = /<br\s*\/?>/gi;
class UnknownDiagramError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "UnknownDiagramError";
  }
}
const defaultConfigFrozen = Object.freeze(defaultConfig);
const setConfigAlias = setConfig;
const setupGraphViewboxAlias = setupGraphViewbox;
const getConfigAlias = getConfig;
export {
  sanitizeHtml,
  initChunkICPOFSXXCurrent as initMermaidCommonRuntime,
  saveConfigFromInitialize,
  getDiagramTitle,
  getUrl,
  getThemeVariables,
  renderKatexSanitized,
  setDiagramTitle,
  setAccTitle,
  resetConfig,
  setupGraphViewbox,
  setSiteConfig,
  sanitizeDirective,
  parseGenericTypes,
  registerDiagram,
  getUserDefinedConfig,
  registerLazyLoadedDiagrams,
  initChunkICPOFSXXDomPurifyRuntime as initDomPurifyRuntime,
  sanitizeTextWithConfig,
  getDiagramLoader,
  getSiteConfig,
  setConfig,
  setAccDescription,
  setConfigAlias,
  themeRegistry,
  getStyles,
  updateSiteConfig,
  getAccDescription,
  clearCommonDb,
  getConfig,
  configureSvgSize,
  defaultConfig,
  detectType,
  frontMatterRegex,
  evaluate,
  calculateMathMLDimensions,
  lineBreakRegex,
  hasKatex,
  defaultConfigFrozen,
  directiveRegex,
  addDirective,
  commonDb,
  diagramDetectors,
  setupGraphViewboxAlias,
  assignWithDepth,
  commonUtils,
  UnknownDiagramError,
  defaultConfigFrozen as defaultConfigAlias,
  getAccTitle,
  getEffectiveHtmlLabels,
  getDiagram,
  getConfigAlias,
  sanitizeText,
};
