// Restored from ref/webview/assets/chunk-ICPOFSXX-DR5eNcWR.js
// Current Mermaid common-runtime surface backed by the restored vendor runtime.
import {
  addDirective,
  assignWithDepth_default as assignWithDepth,
  calculateMathMLDimensions,
  clear as clearCommonDb,
  common_default as commonUtils,
  commonDb_exports as commonDb,
  configureSvgSize,
  defaultConfig,
  detectType,
  detectors as diagramDetectors,
  evaluate,
  getAccDescription,
  getAccTitle,
  getConfig,
  getConfig2 as getConfigAlias,
  getDiagram,
  getDiagramLoader,
  getDiagramTitle,
  getEffectiveHtmlLabels,
  getSiteConfig,
  getThemeVariables,
  getUrl,
  getUserDefinedConfig,
  hasKatex,
  parseGenericTypes,
  registerDiagram,
  registerLazyLoadedDiagrams,
  renderKatexSanitized,
  reset as resetConfig,
  sanitizeDirective,
  sanitizeText as sanitizeTextWithConfig,
  sanitizeText2,
  saveConfigFromInitialize,
  setAccDescription,
  setAccTitle,
  setConfig,
  setDiagramTitle,
  setSiteConfig,
  setupGraphViewbox,
  setupGraphViewbox2 as setupGraphViewboxAlias,
  styles_default as getStyles,
  themes_default as themeRegistry,
  updateSiteConfig,
} from "mermaid-k5/dist/chunks/mermaid.core/chunk-ICPOFSXX.mjs";
function initChunkICPOFSXXCurrent(): void {}
function initChunkICPOFSXXDomPurifyRuntime(): void {}
const sanitizeHtml = sanitizeText2;
const sanitizeText = sanitizeText2;
const frontMatterRegex = /^-{3}\s*[\n\r](.*?)[\n\r]-{3}\s*[\n\r]+/s;
const directiveRegex =
  /%{2}{\s*(?:(\w+)\s*:|(\w+))\s*(?:(\w+)|((?:(?!}%{2}).|\r?\n)*))?\s*(?:}%{2})?/gi;
const lineBreakRegex = /<br\s*\/?>/gi;
class UnknownDiagramError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "UnknownDiagramError";
  }
}
const defaultConfigFrozen = Object.freeze(defaultConfig);
const setConfigAlias = setConfig;
export {
  sanitizeHtml,
  initChunkICPOFSXXCurrent as initMermaidCommonRuntime,
  saveConfigFromInitialize,
  getDiagramTitle,
  getUrl,
  getThemeVariables,
  renderKatexSanitized,
  setDiagramTitle,
  setAccTitle,
  resetConfig,
  setupGraphViewbox,
  setSiteConfig,
  sanitizeDirective,
  parseGenericTypes,
  registerDiagram,
  getUserDefinedConfig,
  registerLazyLoadedDiagrams,
  initChunkICPOFSXXDomPurifyRuntime as initDomPurifyRuntime,
  sanitizeTextWithConfig,
  getDiagramLoader,
  getSiteConfig,
  setConfig,
  setAccDescription,
  setConfigAlias,
  themeRegistry,
  getStyles,
  updateSiteConfig,
  getAccDescription,
  clearCommonDb,
  getConfig,
  configureSvgSize,
  defaultConfig,
  detectType,
  frontMatterRegex,
  evaluate,
  calculateMathMLDimensions,
  lineBreakRegex,
  hasKatex,
  defaultConfigFrozen,
  directiveRegex,
  addDirective,
  commonDb,
  diagramDetectors,
  setupGraphViewboxAlias,
  assignWithDepth,
  commonUtils,
  UnknownDiagramError,
  defaultConfigFrozen as defaultConfigAlias,
  getAccTitle,
  getEffectiveHtmlLabels,
  getDiagram,
  getConfigAlias,
  sanitizeText,
};
