// Restored from ref/webview/assets/address-utils-xK0e4BjB.js
// Current-build entry reusing the byte-identical prior semantic module.
import {
  pixelsToColumnWidth,
  normalizeCellReference,
  decodeRow,
  parseFormulaReference,
  columnWidthToPixels,
  decodeColumn,
  rowHeightPointsToPixels,
  initXlsxAddressUtilsConstantsChunk,
  encodeCellAddress,
  DEFAULT_XLSX_COLUMN_WIDTH,
  getIndexedColor,
  encodeCellRange,
  parseCellRangeReference,
  encodeColumn,
  initXlsxAddressUtilsChunk,
  rangesOverlap,
  getRangeSize,
  normalizeXlsxColor,
  pixelsToRowHeightPoints,
  getCellPadding,
} from "../../../vendor/xlsx-address-utils";
export {
  pixelsToColumnWidth,
  normalizeCellReference,
  decodeRow,
  parseFormulaReference,
  columnWidthToPixels,
  decodeColumn,
  rowHeightPointsToPixels,
  initXlsxAddressUtilsConstantsChunk,
  encodeCellAddress,
  DEFAULT_XLSX_COLUMN_WIDTH,
  getIndexedColor,
  encodeCellRange,
  parseCellRangeReference,
  encodeColumn,
  initXlsxAddressUtilsChunk,
  rangesOverlap,
  getRangeSize,
  normalizeXlsxColor,
  pixelsToRowHeightPoints,
  getCellPadding,
};
