// Restored from ref/webview/assets/document-Boqo1QLQ.js
export {
  Artifact,
  ArtifactType,
  ColumnLayout,
  Comment,
  CommentReference,
  Document,
  DocumentGrid,
  DocumentSection,
  DocumentSettings,
  EmbeddedFont,
  EmbeddedFontType,
  Endnote,
  FontDefinition,
  Footnote,
  HeaderFooterContent,
  NoteProperties,
  NumberingDefinition,
  NumberingLevel,
  PageMargin,
  PageSetup,
  ParagraphNumbering,
  Playground,
  SectionBreakType,
  protobufPackage,
} from "../document-schema-current";
